# Generated by Django 5.2 on 2025-05-11 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rol_alter_usuario_options_alter_usuario_rut_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='CORE_USUARIOS',
        ),
    ]
