# Generated by Django 5.2 on 2025-05-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
