# Generated by Django 5.2 on 2025-05-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
